fly_bbs/controllers/bbs_front.py
from flask import Blueprint, render_template,flash, request, url_for, current_app, session, jsonify, abort, redirect
from fly_bbs import db_utils, utils, forms, models, code_msg
from fly_bbs.extensions import mongo, whoosh_searcher, cache, clear_cache
from flask_login import login_required
from flask_login import current_user
from bson.objectid import ObjectId
import pymongo
from datetime import datetime
from whoosh import query,sorting, qparser


bbs_index = Blueprint("index", __name__, url_prefix="", template_folder="templates")


@bbs_index.route('/')
@bbs_index.route('/page/<int:pn>/size/<int:size>')
@bbs_index.route('/page/<int:pn>')
@bbs_index.route("/catalog/<ObjectId:catalog_id>")
@bbs_index.route("/catalog/<ObjectId:catalog_id>/page/<int:pn>")
@bbs_index.route("/catalog/<ObjectId:catalog_id>/page/<int:pn>/size/<int:size>")
@cache.cached(timeout=2 * 60, key_prefix=utils.gen_cache_key)
def index(pn=1, size=10, catalog_id=None):
    # flash("asdsdsad")

    print(datetime.now())
    sort_key = request.values.get('sort_key', '_id')
    sort_by = (sort_key, pymongo.DESCENDING)
    post_type = request.values.get('type')
    filter1 = {}
    if post_type == 'not_closed':
        filter1['is_closed'] = {'$ne': True}
    if post_type == 'is_closed':
        filter1['is_closed'] = True
    if post_type == 'is_cream':
        filter1['is_cream'] = True
    if catalog_id:
        filter1['catalog_id'] = catalog_id
    page = db_utils.get_page('posts', pn=pn, filter1=filter1, size=size, sort_by=sort_by)
    # print(page)
    return render_template("post_list.html", is_index=catalog_id is None, page=page, sort_key=sort_key
                           , catalog_id=catalog_id, post_type=post_type)


@bbs_index.route('/add', methods=['GET', 'POST'])
@bbs_index.route('/edit/<ObjectId:post_id>', methods=['GET', 'POST'])
@login_required
@clear_cache
def add(post_id=None):
    posts_form = forms.PostsForm()
    if posts_form.is_submitted():
        if not posts_form.validate():
            return jsonify(models.BaseResult(1, str(posts_form.errors)))
        utils.verify_num(posts_form.vercode.data)

        user = current_user.user
        if not user.get('is_active', False) or user.get('is_disabled', False):
            return jsonify(code_msg.USER_UN_ACTIVE_OR_DISABLED)

        user_coin = user.get('coin', 0)
        if posts_form.reward.data > user_coin:
            return jsonify(models.R.ok('悬赏金币不能大于拥有的金币，当前账号金币为：' + str(user_coin)))
        posts = {
            'title': posts_form.title.data,
            'catalog_id': ObjectId(posts_form.catalog_id.data),
            # 'is_closed': False,
            'content': posts_form.content.data,
        }

        post_index = posts.copy()
        post_index['catalog_id'] = str(posts['catalog_id'])

        msg = '发帖成功！'
        reward = posts_form.reward.data
        if post_id:
            posts['modify_at'] = datetime.now()
            mongo.db.posts.update_one({'_id': post_id}, {'$set': posts})
            msg = '修改成功！'

        else:
            posts['create_at'] = datetime.utcnow()
            posts['reward'] = reward
            posts['user_id'] = user['_id']
            # 扣除用户发帖悬赏
            if reward > 0:
                mongo.db.users.update_one({'_id': user['_id']}, {'$inc': {'coin': -reward}})
            mongo.db.posts.save(posts)
            post_id = posts['_id']

        # 更新索引文档
        update_index(mongo.db.posts.find_one_or_404({'_id': post_id}))

        return jsonify(models.R.ok(msg).put('action', url_for('index.index')))
    else:
        ver_code = utils.gen_verify_num()
        # session['ver_code'] = ver_code['answer']
        posts = None
        if post_id:
            posts = mongo.db.posts.find_one_or_404({'_id': post_id})
        title = '发帖' if post_id is None else '编辑帖子'
        return render_template('jie/add.html', page_name='jie', ver_code=ver_code['question'], form=posts_form, is_add=(post_id is None), post=posts, title=title)


def update_index(post):
    _id = str(post['_id'])

    post_index = dict()
    post_index['catalog_id'] = str(post['catalog_id'])
    post_index['user_id'] = str(post['user_id'])
    post_index['create_at'] = post['create_at']
    post_index['content'] = post['content']
    post_index['title'] = post['title']

    whoosh_searcher.update_document('posts', {'obj_id': _id}, post_index)


@bbs_index.route('/post/<ObjectId:post_id>/')
@bbs_index.route('/post/<ObjectId:post_id>/page/<int:pn>/')
def post_detail(post_id, pn=1):
    post = mongo.db.posts.find_one_or_404({'_id': post_id})
    if post:
        post['view_count'] = post.get('view_count', 0) + 1
        mongo.db.posts.save(post)
    post['user'] = db_utils.find_one('users', {'_id': post['user_id']}) or {}

    page = db_utils.get_page('comments', pn=pn, size=10, filter1={'post_id': post_id}, sort_by=('is_adopted', -1))
    return render_template('jie/detail.html', post=post, title=post['title'], page_name='jie', comment_page=page, catalog_id=post['catalog_id'])


@bbs_index.route('/jump')
def jump_user():
    username = request.values.get('username')
    if not username:
        abort(404)
    user = mongo.db.users.find_one_or_404({'username': username})
    return redirect('/user/' + str(user['_id']))


@bbs_index.route('/comment/<ObjectId:comment_id>/')
def jump_comment(comment_id):
    comment = mongo.db.comments.find_one_or_404({'_id': comment_id})
    post_id = comment['post_id']
    pn = 1
    if not comment.get('is_adopted',False):
        comment_index = mongo.db.comments.count({'post_id': post_id, '_id': {'$lt': comment_id}})
        pn = comment_index / 10
        if pn == 0 or pn % 10 != 0:
            pn += 1
    return redirect(url_for('index.post_detail', post_id=post_id, pn=pn) + '#item-' + str(comment_id))
    # return redirect('/post/' + str(post_id)  + '/' + str(pn) + '/')


@bbs_index.route('/search')
@bbs_index.route('/search/page/<int:pn>/')
def post_search(pn=1, size=10):
    keyword = request.values.get('kw')
    if keyword is None:
        return render_template('search/list.html', title='搜索', message='搜索关键字不能为空!')
    with whoosh_searcher.get_searcher('posts') as searcher:
        # q = query.Or([query.Term('title', keyword), query.Term('content', keyword)])
        parser = qparser.MultifieldParser(['title', 'content'], whoosh_searcher.get_index('posts').schema)
        q = parser.parse(keyword)
        result = searcher.search_page(q, pagenum=pn, pagelen=size, sortedby=sorting.ScoreFacet())
        result_list = [x.fields() for x in result.results]
        page = models.Page(pn, size, result=result_list, has_more=result.pagecount > pn, total_page=result.pagecount
                           , total=result.total)
        print(page.result)
    # return jsonify(page)
    return render_template('search/list.html', title=keyword + '搜索结果', page=page, kw=keyword)


@bbs_index.route('/refresh/indexes')
def refresh_indexes():
    name = request.values.get('name')
    whoosh_searcher.clear(name)
    writer = whoosh_searcher.get_writer(name)
    for item in mongo.db[name].find({}, ['_id', 'title', 'content', 'create_at', 'user_id', 'catalog_id']):
        item['obj_id'] = str(item['_id'])
        item['user_id'] = str(item['user_id'])
        item['catalog_id'] = str(item['catalog_id'])
        item.pop('_id')
        writer.add_document(**item)
    writer.commit()
    return ''

fly_bbs/controllers/user_view.py
from flask import Blueprint, render_template,flash, request,session,jsonify, url_for, current_app, redirect, abort
from flask_login import login_user, logout_user, login_required, current_user
from fly_bbs import utils,forms, models, db_utils, code_msg
from fly_bbs.extensions import mongo
from bson.objectid import ObjectId
from werkzeug.security import generate_password_hash
from random import randint
from datetime import datetime
user_view = Blueprint("user", __name__, url_prefix="", template_folder="templates")


@user_view.route('/<ObjectId:user_id>')
def user_home(user_id):
    user = mongo.db.users.find_one_or_404({'_id': user_id})
    return render_template('user/home.html', user=user)


@user_view.route('/posts')
@login_required
def user_posts():
    return render_template('user/index.html', user_page='posts', page_name='user')


@user_view.route('/message')
@user_view.route('/message/page/<int:pn>')
@login_required
def user_message(pn=1):
    user = current_user.user
    if user.get('unread', 0) > 0:
        mongo.db.users.update({'_id': user['_id']}, {'$set': {'unread': 0}})
    message_page = db_utils.get_page('messages', pn, filter1={'user_id': user['_id']}, sort_by=('_id', -1))
    return render_template('user/message.html', user_page='message', page_name='user', page=message_page)


@user_view.route('/message/remove', methods=['POST'])
@login_required
def remove_message():
    user = current_user.user
    if request.values.get('all') == 'true':
        mongo.db.messages.delete_many({'user_id': user['_id']})
    elif request.values.get('id'):
        msg_id = ObjectId(request.values.get('id'))
        mongo.db.messages.delete_one({'_id': msg_id})
    return jsonify(models.BaseResult())


@user_view.route('/set', methods=['GET', 'POST'])
@login_required
def user_set():
    if request.method == 'POST':
        include_keys = ['username', 'avatar', 'desc', 'city', 'sex']
        data = request.values
        update_data = {}
        for key in data.keys():
            if key in include_keys:
                update_data[key] = data.get(key)
        # print(update_data)
        mongo.db.users.update({'_id': current_user.user['_id']}, {'$set': data})
        return jsonify(models.BaseResult())
    return render_template('user/set.html', user_page='set', page_name='user', title='基本设置')


@user_view.route('/repass', methods=['POST'])
def user_repass():
    if 'email' in request.values:
        # email = request.values.get('email')
        # ver_code = request.values.get('ver_code')
        # code = request.values.get('code')
        # password = request.values.get('password')
        # repassword = request.values.get('repassword')
        pwd_form = forms.ForgetPasswordForm()
        if not pwd_form.validate():
            return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(pwd_form.errors)))
        email = pwd_form.email.data
        ver_code = pwd_form.vercode.data
        code = pwd_form.code.data
        password = pwd_form.password.data
        # 验证码校验
        utils.verify_num(ver_code)

        # 查询、删除邮箱激活码
        active_code = mongo.db.active_codes.find_one_or_404({'_id': ObjectId(code)})
        mongo.db.active_codes.delete_one({'_id': ObjectId(code)})
        # 更新用户密码
        user = mongo.db.users.update({'_id': active_code['user_id'], 'email': email},
                                     {'$set': {'password': generate_password_hash(password)}})
        # print(user)
        if user['nModified'] == 0:
            return jsonify(code_msg.CHANGE_PWD_FAIL.put('action', url_for('user.login')))
        return jsonify(code_msg.CHANGE_PWD_SUCCESS.put('action', url_for('user.login')))
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    # nowpassword = request.values.get('nowpassword')
    # password = request.values.get('password')
    # repassword = request.values.get('repassword')
    pwd_form = forms.ChangePassWordForm()
    if not pwd_form.validate():
        return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(pwd_form.errors)))
    nowpassword = pwd_form.nowpassword.data
    # print(nowpassword)
    password = pwd_form.password.data
    user = current_user.user
    if not models.User.validate_login(user['password'], nowpassword):
        raise models.GlobalApiException(code_msg.PASSWORD_ERROR)
    mongo.db.users.update({'_id': user['_id']}, {'$set': {'password': generate_password_hash(password)}})
    return jsonify(models.R.ok())


@user_view.route('/forget', methods=['POST', 'GET'])
@user_view.route('/forget/<ObjectId:code>', methods=['POST', 'GET'])
def user_pass_forget(code=None):
    if request.method == 'POST':
        mail_form = forms.SendForgetMailForm()
        if not mail_form.validate():
            return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(mail_form.errors)))
        email = mail_form.email.data
        ver_code = mail_form.vercode.data

        utils.verify_num(ver_code)
        user = mongo.db.users.find_one({'email': email})
        if not user:
            return jsonify(code_msg.USER_NOT_EXIST)
        send_active_email(user['username'], user_id=user['_id'], email=email, is_forget=True)
        return jsonify(code_msg.RE_PWD_MAIL_SEND.put('action', url_for('user.login')))
    has_code = False
    user = None
    if code:
        active_code = mongo.db.active_codes.find_one({'_id': code})
        has_code = True
        if not active_code:
            return render_template('user/forget.html', page_name='user', has_code=True, code_invalid=True)
        user = mongo.db.users.find_one({'_id': active_code['user_id']})

    ver_code = utils.gen_verify_num()
    # session['ver_code'] = ver_code['answer']
    return render_template('user/forget.html', page_name='user', ver_code=ver_code['question']
                           , code=code, has_code=has_code, user=user)


def send_active_email(username, user_id, email, is_forget=False):
    code = mongo.db.active_codes.insert_one({'user_id': user_id})
    if is_forget:
        body = render_template('email/user_repwd.html', url=url_for('user.user_pass_forget', code=code.inserted_id, _external=True))
        utils.send_email(email, '重置密码', body=body)
        return
    body = render_template('email/user_activate.html', username=username,
                           url=url_for('user.user_active', code=code.inserted_id, _external=True))
    utils.send_email(email, '账号激活', body=body)


@user_view.route('/active', methods=['GET', 'POST'])
def user_active():
    if request.method == 'GET':
        code = request.values.get('code')
        if code:
            user_id = mongo.db.active_codes.find_one({'_id': ObjectId(code)})['user_id']
            if user_id:
                mongo.db.active_codes.delete_many({'user_id': ObjectId(user_id)})
                mongo.db.users.update({'_id': user_id}, {"$set": {'is_active': True}})
                user = mongo.db.users.find_one({'_id': ObjectId(user_id)})
                login_user(models.User(user))
                return render_template('user/activate.html')
        if not current_user.is_authenticated:
            abort(403)
        return render_template('user/activate.html')
    if not current_user.is_authenticated:
        abort(403)
    user = current_user.user
    mongo.db.active_codes.delete_many({'user_id': ObjectId(user['_id'])})
    send_active_email(user['username'], user['_id'], user['email'])
    return jsonify(code_msg.RE_ACTIVATE_MAIL_SEND.put('action', url_for('user.active')))


@user_view.route('/reg', methods=['GET', 'POST'])
def register():
    if db_utils.get_option('open_user', {}).get('val') != '1':
        abort(404)
    user_form = forms.RegisterForm()
    if user_form.is_submitted():
        if not user_form.validate():
            return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(user_form.errors)))
        utils.verify_num(user_form.vercode.data)
        user = mongo.db.users.find_one({'email': user_form.email.data})
        if user:
            return jsonify(code_msg.EMAIL_EXIST)
        user = dict({
            'is_active': False,
            'coin': 0,
            'email': user_form.email.data,
            'username': user_form.username.data,
            'vip': 0,
            'reply_count': 0,
            'avatar': url_for('static', filename='images/avatar/' + str(randint(0, 12)) + '.jpg'),
            'password': generate_password_hash(user_form.password.data),
            'create_at': datetime.utcnow()
        })
        mongo.db.users.insert_one(user)
        send_active_email(user['username'], user['_id'], user['email'])
        return jsonify(code_msg.REGISTER_SUCCESS.put('action', url_for('user.login')))
    ver_code = utils.gen_verify_num()
    # session['ver_code'] = ver_code['answer']
    return render_template('user/reg.html', ver_code=ver_code['question'], form=user_form)


@user_view.route('/login', methods=['GET','POST'])
def login():
    user_form = forms.LoginForm()
    if user_form.is_submitted():
        if not user_form.validate():
            return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(user_form.errors)))
        utils.verify_num(user_form.vercode.data)
        user = mongo.db.users.find_one({'email': user_form.email.data})
        if not user:
            return jsonify(code_msg.USER_NOT_EXIST)
        if not models.User.validate_login(user['password'], user_form.password.data):
            raise models.GlobalApiException(code_msg.PASSWORD_ERROR)
        if not user.get('is_active', False):
            return jsonify(code_msg.USER_UN_ACTIVE)
        if user.get('is_disabled', False):
            return jsonify(code_msg.USER_DISABLED)
        login_user(models.User(user))
        action = request.values.get('next')
        if not action:
            action = url_for('index.index')
        return jsonify(code_msg.LOGIN_SUCCESS.put('action', action))
    logout_user()
    ver_code = utils.gen_verify_num()

fly_bbs/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ title or '首页' }}-{{ get_option('title').val or 'PyFly' }}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="keywords" content="{{ get_option('keywords').val }}">
  <meta name="description" content="{{ get_option('description').val }}">
  <link rel="stylesheet" href="/static/layui/css/layui.css">
  <link rel="stylesheet" href="/static/css/global.css">
  {% block other_res %}
  {% endblock %}
</head>
<body>

<div class="fly-header layui-bg-black">
  <div class="layui-container">
    <a class="fly-logo" href="/">
      <img src="{{ get_option('logo').val or '/static/images/logo.png' }}" alt="layui">
    </a>
    <ul class="layui-nav fly-nav layui-hide-xs">
      {% for item in get_list('pages', sort_by=('sort', -1)) %}
        <li class="layui-nav-item layui-this">
          <a href="{{ item.url }}">{{ item.name }} <i class="layui-icon">{{ item.icon_code|safe }}</i>  </a>
        </li>
      {% endfor %}
    </ul>

    <ul class="layui-nav fly-nav-user">

      {% if current_user.is_authenticated %}

        <li class="layui-nav-item">
          <a class="fly-nav-avatar" href="javascript:;">

            <cite class="layui-hide-xs">{{ current_user.user.username }}</cite>
            {% if current_user.user.renzheng %}
              <i class="iconfont icon-renzheng" title="{{ current_user.user.renzheng }}"></i>
            {% endif %}
            {% if current_user.user.get('vip', 0) > 0 %}
              <i class="layui-badge fly-badge-vip">VIP{{ current_user.user.vip }}</i>
            {% endif %}
            <img src="{{ current_user.user.avatar }}">
          </a>
          <dl class="layui-nav-child">
            <dd><a href="{{ url_for('user.user_set') }}"><i class="layui-icon">&#xe620;</i>基本设置</a></dd>
            <dd><a href="{{ url_for('user.user_message') }}"><i class="iconfont icon-tongzhi" style="top: 4px;"></i>我的消息</a></dd>
            <dd><a href="{{ url_for('user.user_home', user_id=current_user.user._id) }}"><i class="layui-icon" style="margin-left: 2px; font-size: 22px;">&#xe68e;</i>我的主页</a>
            </dd>
            <hr style="margin: 5px 0;">
            <dd><a href="{{ url_for('user.logout') }}" style="text-align: center;">退出</a></dd>
          </dl>
        </li>
        {% if current_user.user.get('unread', 0) > 0 %}
          <li class="layui-nav-item">
          <a href="{{ url_for('user.user_message') }}"><span class="layui-badge">{{ current_user.user.unread }}</span></a>
        </li>
        {% endif %}
      {% else %}
        {% if get_option('open_user').val == '1' %}
          <li class="layui-nav-item">
            <a class="iconfont icon-touxiang layui-hide-xs" href="{{ url_for('user.login') }}"></a>
          </li>
          <li class="layui-nav-item">
            <a href="{{ url_for('user.login') }}">登入</a>
          </li>
          <li class="layui-nav-item">
            <a href="{{ url_for('user.register') }}">注册</a>
          </li>
          {#        <li class="layui-nav-item layui-hide-xs">#}
          {#          <a href="/app/qq/" onclick="layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})" title="QQ登入"#}
          {#             class="iconfont icon-qq"></a>#}
          {#        </li>#}
          {#        <li class="layui-nav-item layui-hide-xs">#}
          {#          <a href="/app/weibo/" onclick="layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})" title="微博登入"#}
          {#             class="iconfont icon-weibo"></a>#}
          {#        </li>#}
        {% endif %}
      {% endif %}
    </ul>
  </div>
</div>
{% block body %}

{% endblock %}


<div class="fly-footer">
  <p>{{ get_option('footer').val|safe or 'Power by PyFly' }}</p>
  <p>
    {% for item in get_list('footer_links', sort_by=('sort', -1)) %}
      <a href="{{ item.url }}" target="_blank">{{ item.name }}</a>
    {% endfor %}
  </p>
</div>

<script src="/static/layui/layui.js"></script>

<script>
    layui.cache.page = '{{ page_name if page_name else '' }}';
    layui.cache.user = {
        username: '{{ current_user.user['username'] if current_user.is_authenticated else '游客'}}'
        , uid: '{{ current_user.user['_id'] if current_user.is_authenticated }}'
        , avatar: '{{ current_user.user['avatar'] if current_user.is_authenticated}}'
        , experience: '{{ current_user.user['coin'] if current_user.is_authenticated else '0'}}'
        , sex: '{{ current_user.user.get('sex', '未知') if current_user.is_authenticated else '未知'}}'
    };
    layui.config({
        version: "3.0.0"
        , base: '/static/mods/' //这里实际使用时，建议改成绝对路径
    }).extend({
        fly: 'index'
    }){% block fly_use %}.use('fly');{% endblock %}
</script>

{% block other_js %}
{% endblock %}

</body>
</html>

fly_bbs/templates/posts.html
{% extends 'base.html' %}
{% block body %}
  <div class="fly-panel fly-column">
    <div class="layui-container">
      <ul class="layui-clear">
        <li class="layui-hide-xs {{ 'layui-this' if is_index }}"><a href="/">综合</a></li>
        {% for item in get_list('catalogs', sort_by=('sort_key', 1)) %}
          <li class="layui-hide-xs {{ 'layui-this' if catalog_id == item._id }}"><a
                  href="/catalog/{{ item._id }}">{{ item.name }}</a></li>
        {% endfor %}

        <li class="layui-hide-xs layui-hide-sm layui-show-md-inline-block"><span class="fly-mid"></span></li>
        {% if current_user.is_authenticated %}
          <li class="layui-hide-xs layui-hide-sm layui-show-md-inline-block"><a href="{{ url_for('user.user_posts') }}">我发表的贴</a></li>
          <li class="layui-hide-xs layui-hide-sm layui-show-md-inline-block"><a
                  href="{{ url_for('user.user_posts') + '#collection' }}">我收藏的贴</a></li>
        {% endif %}

      </ul>

      <div class="fly-column-right layui-hide-xs">
        <span class="fly-search"><i class="layui-icon"></i></span>
        <a href="{{ url_for('index.add') }}" class="layui-btn">发表新帖</a>
      </div>
      <div class="layui-hide-sm layui-show-xs-block"
           style="margin-top: -10px; padding-bottom: 10px; text-align: center;">
        <a href="{{ url_for('index.add') }}" class="layui-btn">发表新帖</a>
      </div>
    </div>
  </div>

  <div class="layui-container">
    <div class="layui-row layui-col-space15">

        {% block content %}
        {% endblock %}
      <div class="layui-col-md4">

        {% if is_index %}
          <div class="fly-panel">
            <h3 class="fly-panel-title">温馨通道</h3>
            <ul class="fly-panel-main fly-list-static">
              {% for item in get_list('passageways', sort_by=('sort', -1)) %}
                <li>
                <a href="{{ item.url }}" target="_blank">{{ item.name }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>

            {% if current_user.is_authenticated %}
                <div class="fly-panel fly-signin">
                    <div class="fly-panel-title">
                        签到
                        <i class="fly-mid"></i>
                        <a href="javascript:;" class="fly-link" id="LAY_signinHelp">说明</a>
                    </div>
                    <div class="fly-panel-main fly-signin-main">

                    </div>
                </div>
            {% endif %}


          <div class="fly-panel fly-rank fly-rank-reply" id="LAY_replyRank">
            <h3 class="fly-panel-title">回贴榜</h3>
            <dl>
              <!--<i class="layui-icon fly-loading">&#xe63d;</i>-->
              {% for item in get_list('users', sort_by=('reply_count',-1), size=12) %}
                <dd>
                  <a href="/user/{{ item._id }}">
                    <img src="{{ item.avatar }}"><cite>{{ item.username }}</cite><i>{{ item.get('reply_count', 0) }}次回答</i>
                  </a>
                </dd>
              {% else %}
                <div class="fly-none">没有相关数据</div>
              {% endfor %}
            </dl>
          </div>
        {% endif %}


        <dl class="fly-panel fly-list-one">
          <dt class="fly-panel-title">本周热议</dt>
          {% for item in get_list('posts', sort_by=('comment_count',-1), size=10, filter1={'create_at':{'$gte': date_cal(now(), 7, False)}}) %}
            <dd>
              <a href="/post/{{ item._id }}">{{ item.title }}</a>
              <span><i class="iconfont icon-pinglun1"></i> {{ item.get('comment_count', 0) }}</span>
            </dd>
          {% else %}
            <div class="fly-none">没有相关数据</div>
          {% endfor %}
        </dl>

        <div class="fly-panel">
          <div class="fly-panel-title">
            友情赞助
          </div>
          <div class="fly-panel-main">
            {% for item in get_list('ads', sort_by=('sort', -1)) %}
              <a href="{{ item.url }}" target="_blank" class="fly-zanzhu" style="background-color: {{ item.color|safe or '#5FB878' }};">{{ item.name }}</a>
            {% endfor %}

          </div>
        </div>

        <div class="fly-panel fly-link">
          <h3 class="fly-panel-title">友情链接</h3>
          <dl class="fly-panel-main">
            {% for item in get_list('friend_links', sort_by=('sort', -1)) %}
              <dd><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></dd>
            {% endfor %}
            <dd><a href="mailto:{{ get_option('email').val }}?subject=%E7%94%B3%E8%AF%B7Fly%E7%A4%BE%E5%8C%BA%E5%8F%8B%E9%93%BE"
                   class="fly-link">申请友链</a>
            <dd>
          </dl>
        </div>

      </div>
    </div>
  </div>
{% endblock %}